import hb from "handlebars";
import { basename } from "node:path";

export const defaultAutogeneratedNote = `/**
 * NOTE: This file is auto generated by the @bonfhir/codegen code generator program.
 *
 * Do not edit this file manually.
 * Instead, edit the template file "{{templatePath}}".
 */


`;

export function pushAutogeneratedNote(
  templatePath: string,
  result: string,
  noteTemplate?: string | null | undefined
): string {
  const compiledAutoGeneratedNoteTemplate = hb.compile(
    noteTemplate || defaultAutogeneratedNote
  );

  const note = compiledAutoGeneratedNoteTemplate({
    templatePath: basename(templatePath),
  });

  return note + result;
}
