/**
 * Concepts that indicate how a patient/subscriber authorization signature is obtained and how it is being retained by a provider.
 * http://terminology.hl7.org/ValueSet/v2-0535
 */
export const Hl7VSSignatureCodeCode = {
  /**
   * Signed CMS-1500 claim form on file, e.g., authorization for release of any medical or other information necessary to process this claim and assignment of benefits.
   */
  C: "C",

  /**
   * Signed authorization for release of any medical or other information necessary to process this claim on file.
   */
  S: "S",

  /**
   * Signed authorization for assignment of benefits on file.
   */
  M: "M",

  /**
   * Signature generated by provider because the patient was not physically present for services.
   */
  P: "P",
} as const;

/**
 * https://hl7.org/fhir/valueset-address-type.html
 */
export type Hl7VSSignatureCodeCode =
  typeof Hl7VSSignatureCodeCode[keyof typeof Hl7VSSignatureCodeCode];
